// Generated register defines for layer_params

#ifndef _LAYER_PARAMS_REG_DEFS_
#define _LAYER_PARAMS_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// auto added parameter
#define LAYER_PARAMS_PARAM_FP_OUT 96

// Register width
#define LAYER_PARAMS_PARAM_REG_WIDTH 32

// Common Interrupt Offsets

// properties of the feature map
#define LAYER_PARAMS_FEATURE_MAP(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x0)
#define LAYER_PARAMS_FEATURE_MAP_REG_OFFSET 0x0
#define LAYER_PARAMS_FEATURE_MAP_WIDTH_MASK 0x7f
#define LAYER_PARAMS_FEATURE_MAP_WIDTH_OFFSET 0
#define LAYER_PARAMS_FEATURE_MAP_HEIGHT_MASK 0x7f
#define LAYER_PARAMS_FEATURE_MAP_HEIGHT_OFFSET 8
#define LAYER_PARAMS_FEATURE_MAP_N_I_MASK 0xff
#define LAYER_PARAMS_FEATURE_MAP_N_I_OFFSET 16
#define LAYER_PARAMS_FEATURE_MAP_N_O_MASK 0xff
#define LAYER_PARAMS_FEATURE_MAP_N_O_OFFSET 24

// describes configuration for TCN inference
#define LAYER_PARAMS_TCN(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x4)
#define LAYER_PARAMS_TCN_REG_OFFSET 0x4
#define LAYER_PARAMS_TCN_IS_TCN 0
#define LAYER_PARAMS_TCN_TCN_WIDTH_MASK 0x1f
#define LAYER_PARAMS_TCN_TCN_WIDTH_OFFSET 8
#define LAYER_PARAMS_TCN_TCN_WIDTH_MOD_DIL_MASK 0x1f
#define LAYER_PARAMS_TCN_TCN_WIDTH_MOD_DIL_OFFSET 16
#define LAYER_PARAMS_TCN_TCN_K_MASK 0x3
#define LAYER_PARAMS_TCN_TCN_K_OFFSET 24

// describes kernel width & stride
#define LAYER_PARAMS_KERNEL(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x8)
#define LAYER_PARAMS_KERNEL_REG_OFFSET 0x8
#define LAYER_PARAMS_KERNEL_K_MASK 0x7
#define LAYER_PARAMS_KERNEL_K_OFFSET 0
#define LAYER_PARAMS_KERNEL_PADDING 8
#define LAYER_PARAMS_KERNEL_STRIDE_W_MASK 0x3
#define LAYER_PARAMS_KERNEL_STRIDE_W_OFFSET 16
#define LAYER_PARAMS_KERNEL_STRIDE_H_MASK 0x3
#define LAYER_PARAMS_KERNEL_STRIDE_H_OFFSET 24

// configures pooling layer
#define LAYER_PARAMS_POOLING(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xc)
#define LAYER_PARAMS_POOLING_REG_OFFSET 0xc
#define LAYER_PARAMS_POOLING_EN 0
#define LAYER_PARAMS_POOLING_P_TYPE 8
#define LAYER_PARAMS_POOLING_KERNEL_MASK 0x3
#define LAYER_PARAMS_POOLING_KERNEL_OFFSET 16
#define LAYER_PARAMS_POOLING_PADDING 24

// low and high thresholds for OCUs
#define LAYER_PARAMS_THRESHOLDS(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x10)
#define LAYER_PARAMS_THRESHOLDS_REG_OFFSET 0x10
#define LAYER_PARAMS_THRESHOLDS_TH_LOW_MASK 0x7ff
#define LAYER_PARAMS_THRESHOLDS_TH_LOW_OFFSET 0
#define LAYER_PARAMS_THRESHOLDS_TH_HIGH_MASK 0x7ff
#define LAYER_PARAMS_THRESHOLDS_TH_HIGH_OFFSET 16

// Indicates valid layer parameters
#define LAYER_PARAMS_CTRL1(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x14)
#define LAYER_PARAMS_CTRL1_REG_OFFSET 0x14
#define LAYER_PARAMS_CTRL1_VALID 0

// disables computation if high resp. initiates computation if unset
#define LAYER_PARAMS_CTRL2(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x18)
#define LAYER_PARAMS_CTRL2_REG_OFFSET 0x18
#define LAYER_PARAMS_CTRL2_COMP_DISABLE 0

// indicates whether computation is done
#define LAYER_PARAMS_CTRL3(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x1c)
#define LAYER_PARAMS_CTRL3_REG_OFFSET 0x1c
#define LAYER_PARAMS_CTRL3_COMP_DONE 0

// Stores the output of the OCUs (common parameters)
#define LAYER_PARAMS_FP_OUT_FP_OUT_FIELD_WIDTH 11
#define LAYER_PARAMS_FP_OUT_FP_OUT_FIELDS_PER_REG 2
#define LAYER_PARAMS_FP_OUT_MULTIREG_COUNT 48

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_0(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x20)
#define LAYER_PARAMS_FP_OUT_0_REG_OFFSET 0x20
#define LAYER_PARAMS_FP_OUT_0_FP_OUT_0_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_0_FP_OUT_0_OFFSET 0
#define LAYER_PARAMS_FP_OUT_0_FP_OUT_1_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_0_FP_OUT_1_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_1(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x24)
#define LAYER_PARAMS_FP_OUT_1_REG_OFFSET 0x24
#define LAYER_PARAMS_FP_OUT_1_FP_OUT_2_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_1_FP_OUT_2_OFFSET 0
#define LAYER_PARAMS_FP_OUT_1_FP_OUT_3_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_1_FP_OUT_3_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_2(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x28)
#define LAYER_PARAMS_FP_OUT_2_REG_OFFSET 0x28
#define LAYER_PARAMS_FP_OUT_2_FP_OUT_4_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_2_FP_OUT_4_OFFSET 0
#define LAYER_PARAMS_FP_OUT_2_FP_OUT_5_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_2_FP_OUT_5_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_3(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x2c)
#define LAYER_PARAMS_FP_OUT_3_REG_OFFSET 0x2c
#define LAYER_PARAMS_FP_OUT_3_FP_OUT_6_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_3_FP_OUT_6_OFFSET 0
#define LAYER_PARAMS_FP_OUT_3_FP_OUT_7_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_3_FP_OUT_7_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_4(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x30)
#define LAYER_PARAMS_FP_OUT_4_REG_OFFSET 0x30
#define LAYER_PARAMS_FP_OUT_4_FP_OUT_8_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_4_FP_OUT_8_OFFSET 0
#define LAYER_PARAMS_FP_OUT_4_FP_OUT_9_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_4_FP_OUT_9_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_5(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x34)
#define LAYER_PARAMS_FP_OUT_5_REG_OFFSET 0x34
#define LAYER_PARAMS_FP_OUT_5_FP_OUT_10_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_5_FP_OUT_10_OFFSET 0
#define LAYER_PARAMS_FP_OUT_5_FP_OUT_11_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_5_FP_OUT_11_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_6(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x38)
#define LAYER_PARAMS_FP_OUT_6_REG_OFFSET 0x38
#define LAYER_PARAMS_FP_OUT_6_FP_OUT_12_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_6_FP_OUT_12_OFFSET 0
#define LAYER_PARAMS_FP_OUT_6_FP_OUT_13_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_6_FP_OUT_13_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_7(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x3c)
#define LAYER_PARAMS_FP_OUT_7_REG_OFFSET 0x3c
#define LAYER_PARAMS_FP_OUT_7_FP_OUT_14_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_7_FP_OUT_14_OFFSET 0
#define LAYER_PARAMS_FP_OUT_7_FP_OUT_15_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_7_FP_OUT_15_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_8(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x40)
#define LAYER_PARAMS_FP_OUT_8_REG_OFFSET 0x40
#define LAYER_PARAMS_FP_OUT_8_FP_OUT_16_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_8_FP_OUT_16_OFFSET 0
#define LAYER_PARAMS_FP_OUT_8_FP_OUT_17_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_8_FP_OUT_17_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_9(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x44)
#define LAYER_PARAMS_FP_OUT_9_REG_OFFSET 0x44
#define LAYER_PARAMS_FP_OUT_9_FP_OUT_18_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_9_FP_OUT_18_OFFSET 0
#define LAYER_PARAMS_FP_OUT_9_FP_OUT_19_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_9_FP_OUT_19_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_10(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x48)
#define LAYER_PARAMS_FP_OUT_10_REG_OFFSET 0x48
#define LAYER_PARAMS_FP_OUT_10_FP_OUT_20_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_10_FP_OUT_20_OFFSET 0
#define LAYER_PARAMS_FP_OUT_10_FP_OUT_21_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_10_FP_OUT_21_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_11(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x4c)
#define LAYER_PARAMS_FP_OUT_11_REG_OFFSET 0x4c
#define LAYER_PARAMS_FP_OUT_11_FP_OUT_22_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_11_FP_OUT_22_OFFSET 0
#define LAYER_PARAMS_FP_OUT_11_FP_OUT_23_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_11_FP_OUT_23_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_12(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x50)
#define LAYER_PARAMS_FP_OUT_12_REG_OFFSET 0x50
#define LAYER_PARAMS_FP_OUT_12_FP_OUT_24_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_12_FP_OUT_24_OFFSET 0
#define LAYER_PARAMS_FP_OUT_12_FP_OUT_25_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_12_FP_OUT_25_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_13(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x54)
#define LAYER_PARAMS_FP_OUT_13_REG_OFFSET 0x54
#define LAYER_PARAMS_FP_OUT_13_FP_OUT_26_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_13_FP_OUT_26_OFFSET 0
#define LAYER_PARAMS_FP_OUT_13_FP_OUT_27_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_13_FP_OUT_27_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_14(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x58)
#define LAYER_PARAMS_FP_OUT_14_REG_OFFSET 0x58
#define LAYER_PARAMS_FP_OUT_14_FP_OUT_28_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_14_FP_OUT_28_OFFSET 0
#define LAYER_PARAMS_FP_OUT_14_FP_OUT_29_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_14_FP_OUT_29_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_15(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x5c)
#define LAYER_PARAMS_FP_OUT_15_REG_OFFSET 0x5c
#define LAYER_PARAMS_FP_OUT_15_FP_OUT_30_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_15_FP_OUT_30_OFFSET 0
#define LAYER_PARAMS_FP_OUT_15_FP_OUT_31_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_15_FP_OUT_31_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_16(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x60)
#define LAYER_PARAMS_FP_OUT_16_REG_OFFSET 0x60
#define LAYER_PARAMS_FP_OUT_16_FP_OUT_32_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_16_FP_OUT_32_OFFSET 0
#define LAYER_PARAMS_FP_OUT_16_FP_OUT_33_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_16_FP_OUT_33_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_17(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x64)
#define LAYER_PARAMS_FP_OUT_17_REG_OFFSET 0x64
#define LAYER_PARAMS_FP_OUT_17_FP_OUT_34_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_17_FP_OUT_34_OFFSET 0
#define LAYER_PARAMS_FP_OUT_17_FP_OUT_35_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_17_FP_OUT_35_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_18(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x68)
#define LAYER_PARAMS_FP_OUT_18_REG_OFFSET 0x68
#define LAYER_PARAMS_FP_OUT_18_FP_OUT_36_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_18_FP_OUT_36_OFFSET 0
#define LAYER_PARAMS_FP_OUT_18_FP_OUT_37_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_18_FP_OUT_37_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_19(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x6c)
#define LAYER_PARAMS_FP_OUT_19_REG_OFFSET 0x6c
#define LAYER_PARAMS_FP_OUT_19_FP_OUT_38_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_19_FP_OUT_38_OFFSET 0
#define LAYER_PARAMS_FP_OUT_19_FP_OUT_39_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_19_FP_OUT_39_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_20(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x70)
#define LAYER_PARAMS_FP_OUT_20_REG_OFFSET 0x70
#define LAYER_PARAMS_FP_OUT_20_FP_OUT_40_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_20_FP_OUT_40_OFFSET 0
#define LAYER_PARAMS_FP_OUT_20_FP_OUT_41_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_20_FP_OUT_41_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_21(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x74)
#define LAYER_PARAMS_FP_OUT_21_REG_OFFSET 0x74
#define LAYER_PARAMS_FP_OUT_21_FP_OUT_42_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_21_FP_OUT_42_OFFSET 0
#define LAYER_PARAMS_FP_OUT_21_FP_OUT_43_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_21_FP_OUT_43_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_22(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x78)
#define LAYER_PARAMS_FP_OUT_22_REG_OFFSET 0x78
#define LAYER_PARAMS_FP_OUT_22_FP_OUT_44_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_22_FP_OUT_44_OFFSET 0
#define LAYER_PARAMS_FP_OUT_22_FP_OUT_45_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_22_FP_OUT_45_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_23(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x7c)
#define LAYER_PARAMS_FP_OUT_23_REG_OFFSET 0x7c
#define LAYER_PARAMS_FP_OUT_23_FP_OUT_46_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_23_FP_OUT_46_OFFSET 0
#define LAYER_PARAMS_FP_OUT_23_FP_OUT_47_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_23_FP_OUT_47_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_24(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x80)
#define LAYER_PARAMS_FP_OUT_24_REG_OFFSET 0x80
#define LAYER_PARAMS_FP_OUT_24_FP_OUT_48_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_24_FP_OUT_48_OFFSET 0
#define LAYER_PARAMS_FP_OUT_24_FP_OUT_49_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_24_FP_OUT_49_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_25(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x84)
#define LAYER_PARAMS_FP_OUT_25_REG_OFFSET 0x84
#define LAYER_PARAMS_FP_OUT_25_FP_OUT_50_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_25_FP_OUT_50_OFFSET 0
#define LAYER_PARAMS_FP_OUT_25_FP_OUT_51_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_25_FP_OUT_51_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_26(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x88)
#define LAYER_PARAMS_FP_OUT_26_REG_OFFSET 0x88
#define LAYER_PARAMS_FP_OUT_26_FP_OUT_52_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_26_FP_OUT_52_OFFSET 0
#define LAYER_PARAMS_FP_OUT_26_FP_OUT_53_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_26_FP_OUT_53_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_27(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x8c)
#define LAYER_PARAMS_FP_OUT_27_REG_OFFSET 0x8c
#define LAYER_PARAMS_FP_OUT_27_FP_OUT_54_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_27_FP_OUT_54_OFFSET 0
#define LAYER_PARAMS_FP_OUT_27_FP_OUT_55_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_27_FP_OUT_55_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_28(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x90)
#define LAYER_PARAMS_FP_OUT_28_REG_OFFSET 0x90
#define LAYER_PARAMS_FP_OUT_28_FP_OUT_56_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_28_FP_OUT_56_OFFSET 0
#define LAYER_PARAMS_FP_OUT_28_FP_OUT_57_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_28_FP_OUT_57_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_29(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x94)
#define LAYER_PARAMS_FP_OUT_29_REG_OFFSET 0x94
#define LAYER_PARAMS_FP_OUT_29_FP_OUT_58_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_29_FP_OUT_58_OFFSET 0
#define LAYER_PARAMS_FP_OUT_29_FP_OUT_59_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_29_FP_OUT_59_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_30(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x98)
#define LAYER_PARAMS_FP_OUT_30_REG_OFFSET 0x98
#define LAYER_PARAMS_FP_OUT_30_FP_OUT_60_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_30_FP_OUT_60_OFFSET 0
#define LAYER_PARAMS_FP_OUT_30_FP_OUT_61_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_30_FP_OUT_61_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_31(id) (LAYER_PARAMS##id##_BASE_ADDR + 0x9c)
#define LAYER_PARAMS_FP_OUT_31_REG_OFFSET 0x9c
#define LAYER_PARAMS_FP_OUT_31_FP_OUT_62_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_31_FP_OUT_62_OFFSET 0
#define LAYER_PARAMS_FP_OUT_31_FP_OUT_63_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_31_FP_OUT_63_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_32(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xa0)
#define LAYER_PARAMS_FP_OUT_32_REG_OFFSET 0xa0
#define LAYER_PARAMS_FP_OUT_32_FP_OUT_64_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_32_FP_OUT_64_OFFSET 0
#define LAYER_PARAMS_FP_OUT_32_FP_OUT_65_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_32_FP_OUT_65_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_33(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xa4)
#define LAYER_PARAMS_FP_OUT_33_REG_OFFSET 0xa4
#define LAYER_PARAMS_FP_OUT_33_FP_OUT_66_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_33_FP_OUT_66_OFFSET 0
#define LAYER_PARAMS_FP_OUT_33_FP_OUT_67_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_33_FP_OUT_67_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_34(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xa8)
#define LAYER_PARAMS_FP_OUT_34_REG_OFFSET 0xa8
#define LAYER_PARAMS_FP_OUT_34_FP_OUT_68_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_34_FP_OUT_68_OFFSET 0
#define LAYER_PARAMS_FP_OUT_34_FP_OUT_69_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_34_FP_OUT_69_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_35(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xac)
#define LAYER_PARAMS_FP_OUT_35_REG_OFFSET 0xac
#define LAYER_PARAMS_FP_OUT_35_FP_OUT_70_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_35_FP_OUT_70_OFFSET 0
#define LAYER_PARAMS_FP_OUT_35_FP_OUT_71_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_35_FP_OUT_71_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_36(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xb0)
#define LAYER_PARAMS_FP_OUT_36_REG_OFFSET 0xb0
#define LAYER_PARAMS_FP_OUT_36_FP_OUT_72_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_36_FP_OUT_72_OFFSET 0
#define LAYER_PARAMS_FP_OUT_36_FP_OUT_73_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_36_FP_OUT_73_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_37(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xb4)
#define LAYER_PARAMS_FP_OUT_37_REG_OFFSET 0xb4
#define LAYER_PARAMS_FP_OUT_37_FP_OUT_74_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_37_FP_OUT_74_OFFSET 0
#define LAYER_PARAMS_FP_OUT_37_FP_OUT_75_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_37_FP_OUT_75_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_38(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xb8)
#define LAYER_PARAMS_FP_OUT_38_REG_OFFSET 0xb8
#define LAYER_PARAMS_FP_OUT_38_FP_OUT_76_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_38_FP_OUT_76_OFFSET 0
#define LAYER_PARAMS_FP_OUT_38_FP_OUT_77_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_38_FP_OUT_77_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_39(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xbc)
#define LAYER_PARAMS_FP_OUT_39_REG_OFFSET 0xbc
#define LAYER_PARAMS_FP_OUT_39_FP_OUT_78_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_39_FP_OUT_78_OFFSET 0
#define LAYER_PARAMS_FP_OUT_39_FP_OUT_79_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_39_FP_OUT_79_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_40(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xc0)
#define LAYER_PARAMS_FP_OUT_40_REG_OFFSET 0xc0
#define LAYER_PARAMS_FP_OUT_40_FP_OUT_80_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_40_FP_OUT_80_OFFSET 0
#define LAYER_PARAMS_FP_OUT_40_FP_OUT_81_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_40_FP_OUT_81_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_41(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xc4)
#define LAYER_PARAMS_FP_OUT_41_REG_OFFSET 0xc4
#define LAYER_PARAMS_FP_OUT_41_FP_OUT_82_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_41_FP_OUT_82_OFFSET 0
#define LAYER_PARAMS_FP_OUT_41_FP_OUT_83_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_41_FP_OUT_83_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_42(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xc8)
#define LAYER_PARAMS_FP_OUT_42_REG_OFFSET 0xc8
#define LAYER_PARAMS_FP_OUT_42_FP_OUT_84_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_42_FP_OUT_84_OFFSET 0
#define LAYER_PARAMS_FP_OUT_42_FP_OUT_85_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_42_FP_OUT_85_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_43(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xcc)
#define LAYER_PARAMS_FP_OUT_43_REG_OFFSET 0xcc
#define LAYER_PARAMS_FP_OUT_43_FP_OUT_86_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_43_FP_OUT_86_OFFSET 0
#define LAYER_PARAMS_FP_OUT_43_FP_OUT_87_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_43_FP_OUT_87_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_44(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xd0)
#define LAYER_PARAMS_FP_OUT_44_REG_OFFSET 0xd0
#define LAYER_PARAMS_FP_OUT_44_FP_OUT_88_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_44_FP_OUT_88_OFFSET 0
#define LAYER_PARAMS_FP_OUT_44_FP_OUT_89_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_44_FP_OUT_89_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_45(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xd4)
#define LAYER_PARAMS_FP_OUT_45_REG_OFFSET 0xd4
#define LAYER_PARAMS_FP_OUT_45_FP_OUT_90_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_45_FP_OUT_90_OFFSET 0
#define LAYER_PARAMS_FP_OUT_45_FP_OUT_91_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_45_FP_OUT_91_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_46(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xd8)
#define LAYER_PARAMS_FP_OUT_46_REG_OFFSET 0xd8
#define LAYER_PARAMS_FP_OUT_46_FP_OUT_92_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_46_FP_OUT_92_OFFSET 0
#define LAYER_PARAMS_FP_OUT_46_FP_OUT_93_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_46_FP_OUT_93_OFFSET 11

// Stores the output of the OCUs
#define LAYER_PARAMS_FP_OUT_47(id) (LAYER_PARAMS##id##_BASE_ADDR + 0xdc)
#define LAYER_PARAMS_FP_OUT_47_REG_OFFSET 0xdc
#define LAYER_PARAMS_FP_OUT_47_FP_OUT_94_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_47_FP_OUT_94_OFFSET 0
#define LAYER_PARAMS_FP_OUT_47_FP_OUT_95_MASK 0x7ff
#define LAYER_PARAMS_FP_OUT_47_FP_OUT_95_OFFSET 11

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _LAYER_PARAMS_REG_DEFS_
// End generated register defines for layer_params
